name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  fmt:
     name: fmt
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
     - name: Install rustfmt
       run: rustup component add rustfmt
     - name: Run cargo fmt
       run: cargo fmt --all -- --check

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --color always --all

  deploy-docs:
    runs-on: ubuntu-latest
 #   if: github.ref == 'refs/heads/master'
    needs:
    - test
    steps:
    - uses: actions/checkout@v2
    - name: Create rustdoc
      run: cargo doc
    - name: Deploy to pages
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/doc
    
